#---
:verbose: true
:pidfile: ./shared/tmp/pids/sidekiq.pid
:logfile: ./shared/log/sidekiq.log
:concurrency:  40
#---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :verbose: true
  :concurrency: 5
:queues:
  - critical
  - default
  - low
  - mailers
